name: publish to hex.pm

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-24.04
    container:
      image: erlang:28.0-alpine
    steps:
    -
      name: Prepare
      run: |
           apk update
           apk --no-cache -u add git
    -
      name: git special configs
      run: |
          git config --global --add safe.directory /__w/enats_msg/enats_msg
    -
      name: Check out repository
      uses: actions/checkout@v4
    -
      name: Publish to Hex.pm
      env:
        HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
      run: |
           rebar3 ex_doc
           rebar3 hex publish -r hexpm --yes --replace
